# 완성본 실행해보기

In [2]:
# 1. 현재 notebook이 사용하는 Python 확인
import sys
import torch

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)

Python: /home/cam/.pyenv/versions/connectedml/bin/python
PyTorch: 2.14.0+cu132


In [3]:
# 2. 프로젝트 루트로 이동
%cd ~/Connected-Car-Machine-Learning/assignment-02/gpt_answer

/home/cam/Connected-Car-Machine-Learning/assignment-02/gpt_answer


In [ ]:
# 3. 패키지 설치
%pip install -e .

In [5]:
# 4. Python 프로그램 실행
!{sys.executable} scripts/policy_evaluation.py

Policy Evaluation (1000 iterations)
initial_value = 0.0, gamma = 1.0
tensor([[-59.4286, -57.4286, -54.2857, -51.7143],
        [-57.4286, -54.5714, -49.7143, -45.1429],
        [-54.2857, -49.7143, -40.8571, -30.0000],
        [-51.7143, -45.1429, -30.0000,   0.0000]], dtype=torch.float64)


In [6]:
!{sys.executable} scripts/policy_evaluation.py --initial-value 0

Policy Evaluation (1000 iterations)
initial_value = 0.0, gamma = 1.0
tensor([[-59.4286, -57.4286, -54.2857, -51.7143],
        [-57.4286, -54.5714, -49.7143, -45.1429],
        [-54.2857, -49.7143, -40.8571, -30.0000],
        [-51.7143, -45.1429, -30.0000,   0.0000]], dtype=torch.float64)


In [7]:
!{sys.executable} scripts/policy_evaluation.py --initial-value 10

Policy Evaluation (1000 iterations)
initial_value = 10.0, gamma = 1.0
tensor([[-59.4286, -57.4286, -54.2857, -51.7143],
        [-57.4286, -54.5714, -49.7143, -45.1429],
        [-54.2857, -49.7143, -40.8571, -30.0000],
        [-51.7143, -45.1429, -30.0000,   0.0000]], dtype=torch.float64)


In [8]:
!{sys.executable} scripts/value_iteration.py

Value Iteration (1000 iterations)
initial_value = 0.0, gamma = 1.0
tensor([[-6., -5., -4., -3.],
        [-5., -4., -3., -2.],
        [-4., -3., -2., -1.],
        [-3., -2., -1.,  0.]], dtype=torch.float64)


In [10]:
# 5. 테스트
!{sys.executable} -m pytest -q

...                                                                      [100%]
3 passed in 0.64s


In [11]:
%%bash

git status
git log --oneline -5